services:
  gor-gemilangcondet-db:
    image: postgres:17.5-alpine
    container_name: gor-gemilangcondet-dev-db
    environment:
      POSTGRES_DB: gor-gemilangcondet-dev
      POSTGRES_USER: gor-gemilangcondet-dev
      POSTGRES_PASSWORD: CLI-825.2025X
    ports:
      - "35001:5432"
    volumes:
      - gor-gemilangcondet-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gor-gemilangcondet-dev -d gor-gemilangcondet-dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  gor-gemilangcondet-db:
    driver: local