spring:
  datasource:
    # Gunakan koneksi database di PostgreSQL docker lokal
    url: "jdbc:postgresql://localhost:35001/gor-gemilangcondet-dev"
    url: "jdbc:postgresql://localhost:35001/gor-gemilangcondet-dev"
    username: ${DB_USER:gor-gemilangcondet-dev}
    password: ${DB_PASSWORD:CLI-825.2025X}
  
  jpa:
    # "update": Kalau kamu ubah kodingan Entity, tabel database otomatis berubah
    hibernate:
      ddl-auto: update
    # Tampilkan query SQL di terminal biar tau kodinganmu ngirim apa
    show-sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

# Konfigurasi JWT untuk development (jangan dipakai sama di production!)
app:
  jwt:
    secret: ${JWT_SECRET:RahasiaLokalJanganDipakaiDiProduction1234567890}
    expiration: 86400000 # 24 Jam

  upload:
    dir: uploads/payment-proofs