spring:
  datasource:
    # Gunakan koneksi database di PostgreSQL docker lokal
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  
  jpa:
    # "update": Kalau kamu ubah kodingan Entity, tabel database otomatis berubah
    hibernate:
      ddl-auto: update
    # Tampilkan query SQL di terminal biar tau kodinganmu ngirim apa
    show-sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

# Konfigurasi JWT untuk development (jangan dipakai sama di production!)
app:
  jwt:
    secret: ${JWT_SECRET:dev-secret-key} # Ganti dengan secret yang lebih kuat di production!
    expiration: 86400000 # 24 Jam

  upload:
    dir: uploads/payment-proofs
  fadhil:
    base-url: ${FADHIL_BASE_URL:http://localhost:8080/api}
  cors:
    allowed-origins: http://localhost:3000,http://localhost:3001